apiVersion: v1
data:
  ssh_host_rsa_key.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF7jfvhTWAtxL6RzhB3HFVEnVBPHlUjtdlhlWBhaEtwDH6FshmMHbcwSpzglrYC7Ui5WnkWPvbLQUh+3yGSDoEic4JULG9IooaCfX+nKRuPghYkFWxEPdjRt3REOO6XuhCUVeVzez/s1ZQiUHYNHBs9h2DHJTpXdzDTO1ko4k9EXbIBJipg0zgDIerfxqFcgMyEHdMxwmnMR5toi/0Wu6UMjCZx53nsyRF5TXyxkKAf5DdLP7CbILz5rmErZ2Bnz05dH4ZjmC0HjnT875T4MG6RAD2ruL+8O+46m96XCC/bHHxCdQYmC125JqMvgajg6oKhWI3FLzwMqPw3AE+6PVRiTVNbyoOCASt9F8tTiMif7GGPo9vQsQDnjifWjJLQ6NyvhzTuGuC19HA8qMprDT/08siE/RU60FMvRGbdCMy7QS8l6qaXi0xqwFkKDXKBW7d1AaKMAKcckcXjKSjCqkuizp+Mbqv1rKNjAznnfekY6IUGyPGdPcQSt6uY6f8HtuLj8A3yHyMI2Z0FoFMxt6IRbyqRAyuvb+dMEh6SGq9eGvseDE2Edfz/fJ5e7eRX7O9H7QPtrwjz3dZBwIHa9F08Cshet6Z1qV6x29duEXMVWAfcpwEFDQacaeUx6U/JeEsXw1/yRbDdUeWiLgilqYb7R6jnXrXkdHFPBLQHqCpKQ== root@node2
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: workspace-ssh-host-key-public
