apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workspace
  name: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  strategy: {}
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
      - image: harbor.edgestream.net/library/workspace:latest
        imagePullPolicy: Always
        name: workspace
        securityContext: {
          privileged: true
        }
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: workspace-data
          mountPath: /root
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: false
        - name: ssh-host-key-public
          mountPath: /etc/ssh/ssh_host_rsa_key.pub
          readOnly: true
          subPath: ssh_host_rsa_key.pub
        - name: ssh-host-key-private
          mountPath: /etc/ssh/ssh_host_rsa_key
          readOnly: true
          subPath: ssh_host_rsa_key
      volumes:
      - name: workspace-data
        persistentVolumeClaim:
          claimName: workspace-data
          readOnly: false
      - name: docker-sock
        hostPath:
          path: "/var/run/docker.sock"
      - name: ssh-host-key-public
        configMap:
          name: workspace-ssh-host-key-public
      - name: ssh-host-key-private
        secret:
          secretName: workspace-ssh-host-key-private
          defaultMode: 0400
      terminationGracePeriodSeconds: 0