apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: workspace
  name: workspace-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi