apiVersion: v1
kind: Service
metadata:
  labels:
    app: workspace
  name: workspace
  namespace: default
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: ssh
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: workspace
  type: ClusterIP