apiVersion: v1
kind: Service
metadata:
  labels:
    app: workspace
  name: workspace
  annotations:
    load-balancer.hetzner.cloud/location: "fsn1"
    load-balancer.hetzner.cloud/use-private-ip: "false"
spec:
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: ssh
  selector:
    app: workspace
  type: LoadBalancer