apiVersion: v1
data:
  ssh_host_rsa_key.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDf0mJaZv7BU90VejDJeeCg4i5CMIkZsZzPwNcNlicmK8RYKKllJhTO64al45FTuFHqr5ZaZI0Mf7t5bBDv7kyvwZYi/kJ468lEGlmyHZ4LWhMypziW/flfvL/kvgvjdNlsiQQJvlpi2Q4yJAo3p+5m45EiaCc1vJjn944Ovw2ruk5iSvqy35Z5LkEAM47kUlQ9vah4baI21GlFCL5LzqviLw7REME2w1EQEH9opT7Y1h74U7MqnCBM4BfwjcKeK84qVV/uZXfZK0Wt+DUMk8I/1K3xBnl7F+QgKsxsdtkMJ6lctajhuAPwk8N0e2JEANB9Tr/RENK06I/F1v2gGrJd/ogl2p2W4ShgBLvALb9bpT4rM7jMbfOtcw2TDiIQirnljgJp5QTXvAhhygQBcAe2Vu+7QfZxc/nGlDbVHDGInVGm8dGz515cjoZxoN/6I4SbfZyGF4JjnSVlLQMdUCNUQLTYnRv02THQkRiOppcA+IHpzQwLnmloVvu3FswokChB82zIvY9fQ2hrIYG9mPDr3Fex/1VEbwV9M3DujMunbZATKDdARfc7pmhYR02P/NcZZa5l7l68tIh2szkWdS4ATObyZMotUeqEn8hChFkqcJWJU23pNthdslLwH18RSItr44JzCifV8zxsDWEaEvtS/FWMKF39gPcbqwpdMUOEfQ== marioschmidt@management
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: workspace-ssh-host-key-public
