apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workspace
  name: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  strategy: {}
  template:
    metadata:
      labels:
        app: workspace
    spec:
      initContainers:
      - name: prepare-workspace-data
        image: edgestream/workspace:latest
        imagePullPolicy: Always
        command:
        - /usr/bin/rsync
        - --recursive
        - --archive
        - --update
        - --verbose
        - /home/ubuntu/
        - /mnt
        volumeMounts:
        - name: workspace-data
          mountPath: /mnt
      containers:
      - name: ssh-daemon
        image: edgestream/workspace:latest
        imagePullPolicy: Always
        securityContext: {
          privileged: true
        }
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: workspace-data
          mountPath: /home/ubuntu
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: false
        - name: ssh-host-key-public
          mountPath: /etc/ssh/ssh_host_rsa_key.pub
          readOnly: true
          subPath: ssh_host_rsa_key.pub
        - name: ssh-host-key-private
          mountPath: /etc/ssh/ssh_host_rsa_key
          readOnly: true
          subPath: ssh_host_rsa_key
        - name: ssh-user-key-public
          mountPath: /home/ubuntu/.ssh/authorized_keys
          readOnly: true
          subPath: authorized_keys
        - name: ssh-user-key-public
          mountPath: /home/ubuntu/.ssh/id_rsa.pub
          readOnly: true
          subPath: id_rsa.pub
      volumes:
      - name: workspace-data
        persistentVolumeClaim:
          claimName: workspace-data
          readOnly: false
      - name: docker-sock
        hostPath:
          path: "/var/run/docker.sock"
      - name: ssh-host-key-public
        configMap:
          name: workspace-ssh-host-key-public
      - name: ssh-host-key-private
        secret:
          secretName: workspace-ssh-host-key-private
          defaultMode: 0400
      - name: ssh-user-key-public
        configMap:
          name: workspace-ssh-user-key-public
      terminationGracePeriodSeconds: 1
